#!/usr/bin/env bash

helpFunction()
{
   echo ""
   echo "Usage: $0 -b -p -r"
   echo -e "\t-b Build the project"
   echo -e "\t-p Package and flash the project"
   echo -e "\t-r Run the project"
   exit 1 # Exit script after printing help
}

# Print helpFunction in case parameters are empty
if [ -z "$1" ] 
then
   echo "Some or all of the parameters are not set";
   helpFunction
fi

if [[ ( $1 == "-b" ) ]]
then
   echo "Building the project"
   cd $(dirname $0)
   west build -p auto -b nrf52840dongle_nrf52840
elif [[ ( $1 == "-p" ) ]]
then
   echo "Packaging and flashing the project"
   cd $(dirname $0)
   nrfutil pkg generate --hw-version 52 --sd-req=0x00 \
            --application build/zephyr/zephyr.hex \
            --application-version 1 ahu.zip
    nrfutil dfu usb-serial -pkg ahu.zip -p /dev/ttyACM0
elif [[ ( $1 == "-r" ) ]]
then
   echo "Running the project..."
   sleep 1
   sudo screen /dev/ttyACM0
else
   echo "Some or all of the parameters are not set";
   helpFunction
fi

if [[ ( $2 == "-b" ) ]]
then
   echo "Building the project"
   cd $(dirname $0)
   west build -p auto -b nrf52840dongle_nrf52840
elif [[ ( $2 == "-p" ) ]]
then
   echo "Packaging and flashing the project"
   cd $(dirname $0)
   nrfutil pkg generate --hw-version 52 --sd-req=0x00 \
            --application build/zephyr/zephyr.hex \
            --application-version 1 ahu.zip
    nrfutil dfu usb-serial -pkg ahu.zip -p /dev/ttyACM0
elif [[ ( $2 == "-r" ) ]]
then
   echo "Running the project..."
   sleep 1
   sudo screen /dev/ttyACM0
elif [[ ( -z "$3" ) ]]
then
   exit 1
else
   echo "Some or all of the parameters are incorrectly set";
   helpFunction
fi

if [[ ( $3 == "-b" ) ]]
then
   echo "Building the project"
   cd $(dirname $0)
   west build -p auto -b nrf52840dongle_nrf52840
elif [[ ( $3 == "-p" ) ]]
then
    echo "Packaging and flashing the project"
    cd $(dirname $0)
    nrfutil pkg generate --hw-version 52 --sd-req=0x00 \
            --application build/zephyr/zephyr.hex \
            --application-version 1 ahu.zip

    nrfutil dfu usb-serial -pkg ahu.zip -p /dev/ttyACM0
elif [[ ( $3 == "-r" ) ]]
then
   echo "Running the project..."
   sleep 2
   sudo screen /dev/ttyACM0
elif [[ ( -z "$3" ) ]]
then
   exit 1
else
   echo "Some or all of the parameters are incorrectly set";
   helpFunction
fi








    
