#!/usr/bin/env bash

helpFunction()
{
   echo ""
   echo "Usage: $0 -b -p -r"
   echo ""
   echo "!!Use only 1 parameter at a time!!"
   echo ""
   echo -e "\t-b Build the project"
   echo -e "\t-p Package and flash the project"
   echo -e "\t-r Run the project"
   exit 1 # Exit script after printing help
}

# Print helpFunction in case parameters are empty
if [ -z "$1" ] 
then
   echo "Some or all of the parameters are not set";
   helpFunction
fi

if [[ ( $1 == "-b" ) ]]
then
   echo "Building the project"
   #sed -i 's/bt_set_name.*;/bt_set_name("JM");/' ./src/main.c
   west build -p auto -b thingy52_nrf52832 
elif [[ ( $1 == "-p" ) ]]
then
   echo "Flashing the project"
   #cd $(dirname $0)/ahu
   #nrfutil pkg generate --hw-version 52 --sd-req=0x00 \
   #         --application build/zephyr/zephyr.hex \
   #         --application-version 1 ahu.zip
   # nrfutil dfu usb-serial -pkg ahu.zip -p /dev/ttyACM0
   west flash -r jlink
elif [[ ( $1 == "-r" ) ]]
then
#   echo "Running the project..."
#   sleep 1
#   sudo screen /dev/ttyACM0
echo "Use nrfConnect"
else
   echo "Some or all of the parameters are not set";
   helpFunction
fi










    
